### PR TITLE
Added .gitmodules to a-prime and updated README

### PR DESCRIPTION
**Pull request by milenaveneziani**
This is a very simple PR that adds the .gitmodules file for MPAS-Analysis and updates the README to take into account recent changes to the repo.
It was also intended to check that everything went well with the creation of the new repo.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@kevans32, @salilmahajan: this is the new a-prime repo. As you can see, the only thing missing was the .gitmodules file that used to be in the main PreAndPostProcessingScripts directory. I added it here and also updated the README file.
Could you clone the new repo and run a quick test? 
My own test passed on edison.

**Comment by kevans32** [comment]
So when testing, 
ON RHEA

it no longer lets me check out the MPAS-Analysis sub module.

Cloning into '/autofs/nccs-svm1_home1/4ue/a-prime/python/MPAS-Analysis'...
Permission denied (publickey).
fatal: Could not read from remote repository.

We saw this before! Unlike before I can do this: 
"git clone https://github.com/MPAS-Dev/MPAS-Analysis.git" elsewhere on my machine successfully. 
@xylar also had me redo my keys , but still no dice.

ON EDISON:
similar but slightly different wording in error:
No submodule mapping found in .gitmodules for path 'python/MPAS-Analysis'
No submodule mapping found in .gitmodules for path 'python/MPAS-Analysis'
MPAS-Analysis submodule: 
python: can't open file 'python/MPAS-Analysis/run_analysis.py': [Errno 2] No such file or directory

Where have you run this successfully? Thanks!

**Comment by milenaveneziani** [comment]
oh, why can't the simple things just work? :)

I ran on edison. No problem.

Could you point me to your cloned folders, on both machines?
I am particularly intrigued by the message on edison..

Also, I suppose you had no problem cloning a-prime? Did you checkout the branch for this PR (or maybe merged it to your local master): origin/add_git_modules ?

**Comment by rljacob** [comment]
To "check out" a submodule, do "git submodule init"

**Comment by kevans32** [comment]
$HOME/4ue/a-prime. Opened up permissions...
/global/homes/e/evanskj/a-prime

yup, Rob, we do that, in fact that is what generates the error on Edison. 
No submodule mapping found in .gitmodules for path 'python/MPAS-Analysis'
On rhea, it does not do anything.

**Comment by rljacob** [comment]
Did you switch to the add_git_modules branch?

**Comment by kevans32** [comment]
I merged that branch into my local master.

**Comment by kevans32** [comment]
Oh wait- maybe I did that on the machine I did NOT merge.... aha! standby

**Comment by rljacob** [comment]
I also had to do "git submodule update" to get the code but it worked on edison for me.

**Comment by kevans32** [comment]
So now I get a similar error on both machines. The problem is ME. What to do? I got new keys, and I can check out MPAS-Analysis outside of a-prime.

Submodule 'python/MPAS-Analysis' (git@github.com:MPAS-Dev/MPAS-Analysis.git) registered for path 'python/MPAS-Analysis'
Cloning into 'python/MPAS-Analysis'...
Enter passphrase for key '/global/homes/e/evanskj/.ssh/id_rsa': 
Received disconnect from 192.30.255.113: 11: Bye Bye
Disconnected from 192.30.255.113
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by rljacob** [comment]
try "ssh -T git@github.com" to verify you can authenticate.   If you can't, its a key problem.

**Comment by milenaveneziani** [comment]
I remember you had this issue before, @kevans32, especially on edison. Do you recall how it was solved?

**Comment by kevans32** [comment]
Going here and doing this fixed it last time.
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

But it is not working this time. AND MY KEYS SHOULD ALREADY BE GOOD.

**Comment by rljacob** [comment]
You can clone a-prime
You can clone MPAS-Analysis
but you can't init the MPAS-Analysis submodule within a-prime.

I'm stumped.    Can you init the submodule on any other platform?   What does "git --version" on edison?

**Comment by milenaveneziani** [comment]
my only other suggestion would be to make a fresh clone, checkout the add_git_modules branch, and then simply run `git submodule update --init` from there without going through the run script.. But maybe you have already tried this.

**Comment by kevans32** [comment]
Ok so its a new day. I remade keys, readded them to GitHub, recloned the repo, cleaned out my fridge, and tried again. It worked! I will merge.

**Comment by philipwjones** [comment]
Definitely the fridge. Probably should be added to any documentation. Also, doesn't hurt to ask for intervention from Saint Isidore of Seville, the patron saint of software and the internet.

**Comment by milenaveneziani** [comment]
yeah! Thanks Kate!

**Pull request merged**
