### PR TITLE
Add MPAS-Analysis v0.5

### PR DESCRIPTION
**Pull request by milenaveneziani**
Updates MPAS-Analysis with v0.5 tag, including switch to ncclimo for computing climatologies and support for T,S,OHC anomaly trends with depth. There are also some plot improvements for the ocn/sea-ice time series and the sea-ice climatologies.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
I have tested this on edison and titan. Results from the titan test can be found here:
http://projects.olcf.ornl.gov/acme/milena/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_years6-10_vs_obs/

**Comment by milenaveneziani** [comment]
@salilmahajan: would it be possible to test this on edison and maybe rhea? For reference, you could use my driver examples (especially important at OLCF, where we need to point to a newer run, a beta2 data set that I transferred to the cli115 directory today. This is because MPAS-Analysis v0.5 only works for ACME versions that are beta1 and newer, and we have pointed to a beta0 run at OLCF so far):
1) on OLCF: `/lustre/atlas1/cli115/proj-shared/milena/a-prime/run_aprime_mv_titan.bash`
2) on edison: `~milena/a-prime/run_aprime_mv.bash`

I will test on aims/acme1 once I have some beta2 data over there.

**Comment by salilmahajan** [comment]
Hi @milenaveneziani, I just ran it on edison by copying your script. The T, S and OHC plots are not showing up on the webpage. Here is the directory:
/global/project/projectdirs/acme/salil/coupled_diagnostics/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_vs_obs

**Comment by milenaveneziani** [comment]
@salilmahajan: could you open up permissions for that directory? thanks.

**Comment by salilmahajan** [comment]
Sorry, just did. Also, I ran the script a second time and the plots show up now. I am not sure, why.


http://portal.nersc.gov/project/acme/salil/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison_years101-110_vs_obs/?


________________________________

**Comment by milenaveneziani** [comment]
I still don't have permission. I think the problem is in the `coupled_diagnostics/` directory.

good that the plots are there now! I can try to decipher the log files to see if there is an indication of the earlier problem.

**Comment by salilmahajan** [comment]
Can you try it again. I have also changed the group to acme.


________________________________

**Comment by milenaveneziani** [comment]
great, thanks.

I forgot that we don't get any log files from mpas-analysis when we run on the login node (this should change soon btw). Anyways, I compared the config files that you used in the 2 runs and they are identical. Did you notice anything unusual (errors/warnings) during the first run, right after the 'Compute OHC timeseries' text?

I am transferring data to acme1, so I will test there as soon as the transfer is done.

**Comment by salilmahajan** [comment]
?No, there was nothing unusual that I could tell.


I just ran it again with different years on edison and it passed with all plots showing up. I will run it at OLCF next.


________________________________

**Comment by milenaveneziani** [comment]
test on acme1 passed.

**Comment by milenaveneziani** [comment]
@salilmahajan: if your test at OLCF goes well, I think we can merge this.

**Comment by salilmahajan** [comment]
?Yes, it ran on Rhea and all the plots are there.


________________________________

**Comment by salilmahajan** [comment]
?Hi Milena, I ran the scripts in the batch mode on edison. All works fine but I get permission errors on all links on the webpage.



________________________________

**Comment by milenaveneziani** [comment]
> I ran the scripts in the batch mode on edison. All works fine but I get permission errors on all links on the webpage.

hmm, I don't remember this problem before. Let me also try it.

**Comment by milenaveneziani** [comment]
@salilmahajan: I fixed the html permission problem. Now I need to add the license headers and then this will be ready to merge. I will let you know when that's done.

**Comment by milenaveneziani** [comment]
@salilmahajan: this is ready to be merged. Missing license headers have been added. Tests have passed on all machines.

**Comment by milenaveneziani** [comment]
Thanks @salilmahajan!

**Comment by xylar** [comment]
Congratulations!  That went faster than normal.

**Pull request merged**
